#############################
###   HATCHERY
#############################


### hatchery : setupBatch :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6InNldHVwQmF0Y2giLCJvcmlnaW5zIjpbXX0.W_uyNjjnUASbpkzzXJnr4ODUBgU2LPMI9spgNPPSUQcwlSMUl0hGbibBE8TFJ8NF9PB_oDS4KHuiIffMpmzi6g



### hatchery : VERIFY setupBatch :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6InNldHVwQmF0Y2giLCJvcmlnaW5zIjpbXX0.W_uyNjjnUASbpkzzXJnr4ODUBgU2LPMI9spgNPPSUQcwlSMUl0hGbibBE8TFJ8NF9PB_oDS4KHuiIffMpmzi6g



### hatchery : pushData :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsImJyZWVkZXJJZCI6ImJyZWVkZXIwMDEiLCJmYXJtZXJTZXR1cERhdGUiOjE2NTY1NDc1NjgsImhhdGNoZXJ5S2lwSWQiOiIxMjM0NS0xMjM0LTEyMzQiLCJvcE5hbWUiOiJwdXNoSGF0Y2hlcnlEYXRhIiwicmFjZSI6Ikh1YmJhcmQgSkEtNzU3IFByb0NhcmUiLCJ1bml0cyI6Mjk3ODB9.74KzOhkdX22cDUI2eYXySbUvscGrh7JLesHQhqrgwDA20fT087YlRmctCcds9VQRPgG0cIJ6TlQ7L7HcBlv7SQ



### hatchery : VERIFY pushData :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsImJyZWVkZXJJZCI6ImJyZWVkZXIwMDEiLCJmYXJtZXJTZXR1cERhdGUiOjE2NTY1NDc1NjgsImhhdGNoZXJ5S2lwSWQiOiIxMjM0NS0xMjM0LTEyMzQiLCJvcE5hbWUiOiJwdXNoSGF0Y2hlcnlEYXRhIiwicmFjZSI6Ikh1YmJhcmQgSkEtNzU3IFByb0NhcmUiLCJ1bml0cyI6Mjk3ODB9.74KzOhkdX22cDUI2eYXySbUvscGrh7JLesHQhqrgwDA20fT087YlRmctCcds9VQRPgG0cIJ6TlQ7L7HcBlv7SQ



### hatchery : releaseBatch :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsImRlc3RpbmF0aW9ucyI6WyIweEVENDU2MDc3RTI4RmU5MmE2NGRkN0NDN0U5MWZlMkE0NzBGYTAzRDAiLCIweDgzYkQ3YzNFMDgyRDUyYTczMGMxOUE1RkYwMGJGZWNFQzA1RWI4RjAiXSwib3BOYW1lIjoicmVsZWFzZUJhdGNoIn0.GpOsNgKUcfv8kM14wiByxddi0LgyaotlQk87TKY1Ckt0f6EPnLVorHDmKZ1DrxvDeaw9NFkSw5XMVOBHjfYWLQ



### hatchery : VERIFY releaseBatch :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsImRlc3RpbmF0aW9ucyI6WyIweEVENDU2MDc3RTI4RmU5MmE2NGRkN0NDN0U5MWZlMkE0NzBGYTAzRDAiLCIweDgzYkQ3YzNFMDgyRDUyYTczMGMxOUE1RkYwMGJGZWNFQzA1RWI4RjAiXSwib3BOYW1lIjoicmVsZWFzZUJhdGNoIn0.GpOsNgKUcfv8kM14wiByxddi0LgyaotlQk87TKY1Ckt0f6EPnLVorHDmKZ1DrxvDeaw9NFkSw5XMVOBHjfYWLQ



### hatchery : releaseBatchWithoutFarmer1 :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsImRlc3RpbmF0aW9ucyI6WyIweDgzYkQ3YzNFMDgyRDUyYTczMGMxOUE1RkYwMGJGZWNFQzA1RWI4RjAiXSwib3BOYW1lIjoicmVsZWFzZUJhdGNoIn0.dmqQHz9buDn1eDre7o-AIxsOYzwBPuSjmyNxSTlxkA11uq0PEBHSxHEyZl1ey1d7A5cDG0VzFQK2VKqqCssX5A



### hatchery : VERIFY releaseBatchWithoutFarmer1 :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsImRlc3RpbmF0aW9ucyI6WyIweDgzYkQ3YzNFMDgyRDUyYTczMGMxOUE1RkYwMGJGZWNFQzA1RWI4RjAiXSwib3BOYW1lIjoicmVsZWFzZUJhdGNoIn0.dmqQHz9buDn1eDre7o-AIxsOYzwBPuSjmyNxSTlxkA11uq0PEBHSxHEyZl1ey1d7A5cDG0VzFQK2VKqqCssX5A



### hatchery : getBatch :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6ImdldEJhdGNoIn0.mA6Vdjy4gPFWP8cbIKPNsZa31OCKPMJgRh6ouJ614mliUMLpMF-Yc-OzILtxuHaELhgZTNz-NQxGOqSfbAzlmQ



### hatchery : getProductionChain :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6ImdldFByb2R1Y3Rpb25DaGFpbiJ9.WDaXaxZyLPb7K7CLLyarh_HIekwhuR0iA7PaMQFGMMxxSGPL2b15AoJdVO2w8c4g1M8SvJab3yicIbNoDM2Qqw



### hatchery : searchNotarization using a regex string :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6ImZpbmROb3Rhcml6YXRpb25zIiwicXVlcnkiOnsicmFjZSI6Ikh1YiJ9fQ.rdYoowVbDB-48BzMY74rCYQH3e3yGbEtFgSxHRR1Fx5GiwRCmgvsV9dOMFmIixqbr1tC6ovW4CisSVQECIcV9Q



### hatchery : searchNotarization using exact number :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6ImZpbmROb3Rhcml6YXRpb25zIiwicXVlcnkiOnsidW5pdHMiOjI5NzgwfX0.AmDBDaYPbturDvK8bCM2DT5c2KTWmajykPwN30Tx08gT50QeHu56hJyvKM8hwL9mEdD2mtChz1JLPNli3MHYwA



### hatchery : searchNotarization using multi keys (AND) :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6ImZpbmROb3Rhcml6YXRpb25zIiwicXVlcnkiOnsicmFjZSI6ImgiLCJ1bml0cyI6Mjk3ODB9fQ._3-AMWR3oafPBjvzSJ1ot0CFujQQ4Dem8VyFqhc29LFWrTyvyNlVNoAsY1JRMiH6ey_8cnXjvlDFsleK0MXQrQ



### hatchery : searchNotarization using empty string => 400 :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6ImZpbmROb3Rhcml6YXRpb25zIiwicXVlcnkiOnsicmFjZSI6IiJ9fQ.0qgJtK-vdiqFsuG3oMjdwlZj_HoqTd4PqUFq5hO6mqNmnWEOcenZ_kWCl8eikyRSSx6Ja2KEE-x6VHPIS1CLkA



### hatchery : searchNotarization using nested object => 400 :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6ImZpbmROb3Rhcml6YXRpb25zIiwicXVlcnkiOnsibmVzdGVkIjp7InNvbWV0aGluZyI6ImhlbGxvIn19fQ.bOpW8mWyg56ylakdCVAMFRihnZIyO3XyNA2cgoGw4dFMHRzMCTxYZux3Dejlu54j9hJlbJVI1y0YEZfsitfKRw



### hatchery : searchNotarization using array => supported for one flat value from the array :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6ImZpbmROb3Rhcml6YXRpb25zIiwicXVlcnkiOnsiZGVzdGluYXRpb25zIjoiMHhFRDQ1NjA3N0UyOEZlOTJhNjRkZDdDQzdFOTFmZTJBNDcwRmEwM0QwIn19.WtBS_Occ0SV0_iCW78jU5n0JXaf3VeMCwcinBw6-6R57K0aWgLcrfBBIyuVQSfcM6S5QG1BTZWeJ7LLLVA967A



### hatchery : searchNotarization using multiple same key => json parser keeps last key only (object cannot have duplicate keys) :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6ImZpbmROb3Rhcml6YXRpb25zIiwicXVlcnkiOnsiZGVzdGluYXRpb25zIjoiMHg4M2JEN2MzRTA4MkQ1MmE3MzBjMTlBNUZGMDBiRmVjRUMwNUViOEYwIn19.8N4yk-52XZ9AWy_GvfVtSmapv9KxRKa5WMdOSoAFv7o-5yJy93x9gvEyrh_BkUfVIMvScxJX31IuhU468vWBkA



### hatchery : searchNotarization using array => unsupported key with array value :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6ImZpbmROb3Rhcml6YXRpb25zIiwicXVlcnkiOnsiZGVzdGluYXRpb25zIjpbIjB4RUQ0NTYwNzdFMjhGZTkyYTY0ZGQ3Q0M3RTkxZmUyQTQ3MEZhMDNEMCIsIjB4ODNiRDdjM0UwODJENTJhNzMwYzE5QTVGRjAwYkZlY0VDMDVFYjhGMCJdfX0.T2ToZEBYt6wDIzz7ZBKrgHBUBKtnRny-SyuqizAdX8xOit03mZK4CdpNz2oJBjFejzFJRzJj0ecYhEJ4wQvoEg



### hatchery : token with invalid opName :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6InNvbWV0aGluZyIsInF1ZXJ5Ijp7ImRlc3RpbmF0aW9ucyI6WyIweDgzYkQ3YzNFMDgyRDUyYTczMGMxOUE1RkYwMGJGZWNFQzA1RWI4RjAiXX19.lgVKrhP1HcXcNBUgd51_S0C1Vp1T1taAb85uZfrSKgEGEFV1pSN1lIqwPOaaj-LZUB_cR8rYb9hREeK-_hvDPA



### hatchery : VERIFY token with invalid opName :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiQ1U2VXU3X1JRdDcycTRRSXNKM3RvTndidTFMQ3doWjZ0cU5ROF9SQjR6WSIsInkiOiJOaHNpZHhIN1BEVjBNb1d6YVZTbDJWM25Jbnh6a3plbFlzM0dGWXVRb2JBIn19.eyJiYXRjaElkIjoiSDFCMSIsIm9wTmFtZSI6InNvbWV0aGluZyIsInF1ZXJ5Ijp7ImRlc3RpbmF0aW9ucyI6WyIweDgzYkQ3YzNFMDgyRDUyYTczMGMxOUE1RkYwMGJGZWNFQzA1RWI4RjAiXX19.lgVKrhP1HcXcNBUgd51_S0C1Vp1T1taAb85uZfrSKgEGEFV1pSN1lIqwPOaaj-LZUB_cR8rYb9hREeK-_hvDPA



#############################
###   FARMER
#############################


### farmer : setupBatch :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiekdqdnFOeVhWc0xLTXl2VEpyQWg2QWlzbFctaHhGR0F1OS1FOHVEYVR6byIsInkiOiJ2b3NVQzdzWFJCODQxSDRaWXJyTlVBWDhkRldxNm82ZU1vN0tEVnhEZnZjIn19.eyJiYXRjaElkIjoiRjFCMSIsIm9wTmFtZSI6InNldHVwQmF0Y2giLCJvcmlnaW5zIjpbIkgxQjEiXX0.rFaGqg4inp8RL0-EzwTJcwnOEjTV54s4Tu2Hanx9f09NEg1uGj_N79ZjPa9XlT0bkNPoGs3Jf4WyiJLQCsxSxA



### farmer : VERIFY setupBatch :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiekdqdnFOeVhWc0xLTXl2VEpyQWg2QWlzbFctaHhGR0F1OS1FOHVEYVR6byIsInkiOiJ2b3NVQzdzWFJCODQxSDRaWXJyTlVBWDhkRldxNm82ZU1vN0tEVnhEZnZjIn19.eyJiYXRjaElkIjoiRjFCMSIsIm9wTmFtZSI6InNldHVwQmF0Y2giLCJvcmlnaW5zIjpbIkgxQjEiXX0.rFaGqg4inp8RL0-EzwTJcwnOEjTV54s4Tu2Hanx9f09NEg1uGj_N79ZjPa9XlT0bkNPoGs3Jf4WyiJLQCsxSxA



### farmer : pushData :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiekdqdnFOeVhWc0xLTXl2VEpyQWg2QWlzbFctaHhGR0F1OS1FOHVEYVR6byIsInkiOiJ2b3NVQzdzWFJCODQxSDRaWXJyTlVBWDhkRldxNm82ZU1vN0tEVnhEZnZjIn19.eyJiYXRjaElkIjoiRjFCMSIsImZhcm1lckhvdXNpbmciOiJOSUctMyIsImZhcm1lcktpcElkIjoiMTIzNDUtMTIzNC0xMTExIiwiZmFybWVyU2V0dXBEYXRlIjoxNjU2NTQ3NTY4LCJvcE5hbWUiOiJwdXNoRmFybWVyRGF0YSIsInJhY2UiOiJIdWJiYXJkIEpBLTc1NyBQcm9DYXJlIiwidW5pdHMiOjE4OTAwfQ.MAVoE09JJChI3xDF-m4uDhprkSUHhV6uO24kpgPT-to35Ol9_Wd-O6V0v5RtTBQvnC4k9aa-JZ8ibWUBoXs8tQ



### farmer : VERIFY pushData :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiekdqdnFOeVhWc0xLTXl2VEpyQWg2QWlzbFctaHhGR0F1OS1FOHVEYVR6byIsInkiOiJ2b3NVQzdzWFJCODQxSDRaWXJyTlVBWDhkRldxNm82ZU1vN0tEVnhEZnZjIn19.eyJiYXRjaElkIjoiRjFCMSIsImZhcm1lckhvdXNpbmciOiJOSUctMyIsImZhcm1lcktpcElkIjoiMTIzNDUtMTIzNC0xMTExIiwiZmFybWVyU2V0dXBEYXRlIjoxNjU2NTQ3NTY4LCJvcE5hbWUiOiJwdXNoRmFybWVyRGF0YSIsInJhY2UiOiJIdWJiYXJkIEpBLTc1NyBQcm9DYXJlIiwidW5pdHMiOjE4OTAwfQ.MAVoE09JJChI3xDF-m4uDhprkSUHhV6uO24kpgPT-to35Ol9_Wd-O6V0v5RtTBQvnC4k9aa-JZ8ibWUBoXs8tQ



### farmer : pushPartialData :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiekdqdnFOeVhWc0xLTXl2VEpyQWg2QWlzbFctaHhGR0F1OS1FOHVEYVR6byIsInkiOiJ2b3NVQzdzWFJCODQxSDRaWXJyTlVBWDhkRldxNm82ZU1vN0tEVnhEZnZjIn19.eyJiYXRjaElkIjoiRjFCMSIsIm9wTmFtZSI6InB1c2hGYXJtZXJEYXRhIiwidW5pdHMiOjE4ODk0fQ.5xfMWGQKrFtQYXq-1lDSO0KYTcSA0yLKorDbHmBJHQ5900kyZ4F8UmWwdZ0R5-b2VBmvmlTf9-N5t-C94ZjBFg



### farmer : VERIFY pushPartialData :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiekdqdnFOeVhWc0xLTXl2VEpyQWg2QWlzbFctaHhGR0F1OS1FOHVEYVR6byIsInkiOiJ2b3NVQzdzWFJCODQxSDRaWXJyTlVBWDhkRldxNm82ZU1vN0tEVnhEZnZjIn19.eyJiYXRjaElkIjoiRjFCMSIsIm9wTmFtZSI6InB1c2hGYXJtZXJEYXRhIiwidW5pdHMiOjE4ODk0fQ.5xfMWGQKrFtQYXq-1lDSO0KYTcSA0yLKorDbHmBJHQ5900kyZ4F8UmWwdZ0R5-b2VBmvmlTf9-N5t-C94ZjBFg



### farmer : orderAnalysis :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiekdqdnFOeVhWc0xLTXl2VEpyQWg2QWlzbFctaHhGR0F1OS1FOHVEYVR6byIsInkiOiJ2b3NVQzdzWFJCODQxSDRaWXJyTlVBWDhkRldxNm82ZU1vN0tEVnhEZnZjIn19.eyJiYXRjaElkIjoiRjFCMSIsImxhYm9yYXRvcnlFdGhlcmV1bUFkZHJlc3MiOiIweEUwNjMxMjIzRjkzMThhOGIxMTg0M2UzRjI0QmQ0MEQzZDFkYzgyRGYiLCJvcE5hbWUiOiJvcmRlckFuYWx5c2lzIiwib3JkZXJJZCI6IkxhYjAwMSJ9.4fKEFiQPHdUrwi26FE9vqAnRj_YmIjyR2sC_bxeKEsMhxx1JMlSAaooRn_EcDLzXuMf5DMi64J7BO7SObJ3HIg



### farmer : VERIFY orderAnalysis :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiekdqdnFOeVhWc0xLTXl2VEpyQWg2QWlzbFctaHhGR0F1OS1FOHVEYVR6byIsInkiOiJ2b3NVQzdzWFJCODQxSDRaWXJyTlVBWDhkRldxNm82ZU1vN0tEVnhEZnZjIn19.eyJiYXRjaElkIjoiRjFCMSIsImxhYm9yYXRvcnlFdGhlcmV1bUFkZHJlc3MiOiIweEUwNjMxMjIzRjkzMThhOGIxMTg0M2UzRjI0QmQ0MEQzZDFkYzgyRGYiLCJvcE5hbWUiOiJvcmRlckFuYWx5c2lzIiwib3JkZXJJZCI6IkxhYjAwMSJ9.4fKEFiQPHdUrwi26FE9vqAnRj_YmIjyR2sC_bxeKEsMhxx1JMlSAaooRn_EcDLzXuMf5DMi64J7BO7SObJ3HIg



### farmer : releaseBatch :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiekdqdnFOeVhWc0xLTXl2VEpyQWg2QWlzbFctaHhGR0F1OS1FOHVEYVR6byIsInkiOiJ2b3NVQzdzWFJCODQxSDRaWXJyTlVBWDhkRldxNm82ZU1vN0tEVnhEZnZjIn19.eyJiYXRjaElkIjoiRjFCMSIsImRlc3RpbmF0aW9ucyI6WyIweDNGMGZBODJEOTkyNjM3MzU5NTY4QjBjRWM4M0M0ZDQwNjczNjcxRTciLCIweDU2RDZkQTg2OTM1RjcxOTY5ZjhmMmI1OTI2QjdhNzVBYjc4MDdhODYiXSwib3BOYW1lIjoicmVsZWFzZUJhdGNoIn0.bLhGsU6PCNPb4pgnfqwv7TcpCdMqVnfaYixx4TeceEkUJjkxty0RqN8_AyR9ls2MgNiA7dBsEeCfcLQEg3OCMQ



### farmer : VERIFY releaseBatch :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiekdqdnFOeVhWc0xLTXl2VEpyQWg2QWlzbFctaHhGR0F1OS1FOHVEYVR6byIsInkiOiJ2b3NVQzdzWFJCODQxSDRaWXJyTlVBWDhkRldxNm82ZU1vN0tEVnhEZnZjIn19.eyJiYXRjaElkIjoiRjFCMSIsImRlc3RpbmF0aW9ucyI6WyIweDNGMGZBODJEOTkyNjM3MzU5NTY4QjBjRWM4M0M0ZDQwNjczNjcxRTciLCIweDU2RDZkQTg2OTM1RjcxOTY5ZjhmMmI1OTI2QjdhNzVBYjc4MDdhODYiXSwib3BOYW1lIjoicmVsZWFzZUJhdGNoIn0.bLhGsU6PCNPb4pgnfqwv7TcpCdMqVnfaYixx4TeceEkUJjkxty0RqN8_AyR9ls2MgNiA7dBsEeCfcLQEg3OCMQ



### farmer : getBatch :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiekdqdnFOeVhWc0xLTXl2VEpyQWg2QWlzbFctaHhGR0F1OS1FOHVEYVR6byIsInkiOiJ2b3NVQzdzWFJCODQxSDRaWXJyTlVBWDhkRldxNm82ZU1vN0tEVnhEZnZjIn19.eyJiYXRjaElkIjoiRjFCMSIsIm9wTmFtZSI6ImdldEJhdGNoIn0.w5SU727vhzKgaFXJRcV1ZxzSb1OFCHqaN9GelDfqZBYdqQXNu64n5-I546dlA617BvCFNkwYu3d9GiRsGLNvNw



### farmer : getProductionChain :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiekdqdnFOeVhWc0xLTXl2VEpyQWg2QWlzbFctaHhGR0F1OS1FOHVEYVR6byIsInkiOiJ2b3NVQzdzWFJCODQxSDRaWXJyTlVBWDhkRldxNm82ZU1vN0tEVnhEZnZjIn19.eyJiYXRjaElkIjoiRjFCMSIsIm9wTmFtZSI6ImdldFByb2R1Y3Rpb25DaGFpbiJ9.yf8mOlTQhFKBHtKhPYTSPqFfD9NM5UjdlE0B5Q9rlrkL0FIl3p57jMzBqCEJlu8nVlDjJRBMe-XJ_tjUg-Kgtg



### farmer : searchNotarization using array => supported for one flat value from the array :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiekdqdnFOeVhWc0xLTXl2VEpyQWg2QWlzbFctaHhGR0F1OS1FOHVEYVR6byIsInkiOiJ2b3NVQzdzWFJCODQxSDRaWXJyTlVBWDhkRldxNm82ZU1vN0tEVnhEZnZjIn19.eyJiYXRjaElkIjoiRjFCMSIsIm9wTmFtZSI6ImZpbmROb3Rhcml6YXRpb25zIiwicXVlcnkiOnsib3JpZ2lucyI6IkgxQjEifX0.sYBUofwyeOu-B5sV0VrO7Rc920uW9SvU5BqKOmy9bcghQkA8iqecH22joV5RIFF9qY7fKamLrvawRdqdagVeug



#############################
###   SLAUGHTERHOUSE
#############################


### slaughterhouse : setupBatch :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiTS1tWDlFMW1ySUxPckVIM1BNVi1hSnZ6OEFFQmFVZkxMLXlLWElkUVJ4SSIsInkiOiJpeExJamM1VFczYS1YNEFZdkVrSEx1bm93NGk2NjB3cGNGZnpmdVJzUS1JIn19.eyJiYXRjaElkIjoiUzFCMSIsIm9wTmFtZSI6InNldHVwQmF0Y2giLCJvcmlnaW5zIjpbIkYxQjEiXX0.fkZh7KJOKQC6cdCdNU6ESu3s-tutl-NCleI8dZx1B00wOqHj82Vjtbt19wz1yFweK2tDUhKNRDcMmzL-IG8sAA



### slaughterhouse : VERIFY setupBatch :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiTS1tWDlFMW1ySUxPckVIM1BNVi1hSnZ6OEFFQmFVZkxMLXlLWElkUVJ4SSIsInkiOiJpeExJamM1VFczYS1YNEFZdkVrSEx1bm93NGk2NjB3cGNGZnpmdVJzUS1JIn19.eyJiYXRjaElkIjoiUzFCMSIsIm9wTmFtZSI6InNldHVwQmF0Y2giLCJvcmlnaW5zIjpbIkYxQjEiXX0.fkZh7KJOKQC6cdCdNU6ESu3s-tutl-NCleI8dZx1B00wOqHj82Vjtbt19wz1yFweK2tDUhKNRDcMmzL-IG8sAA



### slaughterhouse : pushData :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiTS1tWDlFMW1ySUxPckVIM1BNVi1hSnZ6OEFFQmFVZkxMLXlLWElkUVJ4SSIsInkiOiJpeExJamM1VFczYS1YNEFZdkVrSEx1bm93NGk2NjB3cGNGZnpmdVJzUS1JIn19.eyJiYXRjaElkIjoiUzFCMSIsImZhcm1lckhvdXNpbmciOiJOSUctMyIsImZhcm1lclNldHVwRGF0ZSI6MTY1NjU0NzU2OCwib3BOYW1lIjoicHVzaFNsYXVnaHRlcmhvdXNlRGF0YSIsInJhY2UiOiJIdWJiYXJkIEpBLTc1NyBQcm9DYXJlIiwic2xhdWdodGVyRGF0ZSI6MTY2ODAzODc2OCwidW5pdHMiOjk4MDB9.gi5sWJn3yGwDugozTxCb7VJiOVCbdip_ATklUKtAzcNWmJ2qe4tJe2w_YPfALMHqnHkv2ulv98Ff3AJ8SJ_rRQ



### slaughterhouse : VERIFY pushData :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiTS1tWDlFMW1ySUxPckVIM1BNVi1hSnZ6OEFFQmFVZkxMLXlLWElkUVJ4SSIsInkiOiJpeExJamM1VFczYS1YNEFZdkVrSEx1bm93NGk2NjB3cGNGZnpmdVJzUS1JIn19.eyJiYXRjaElkIjoiUzFCMSIsImZhcm1lckhvdXNpbmciOiJOSUctMyIsImZhcm1lclNldHVwRGF0ZSI6MTY1NjU0NzU2OCwib3BOYW1lIjoicHVzaFNsYXVnaHRlcmhvdXNlRGF0YSIsInJhY2UiOiJIdWJiYXJkIEpBLTc1NyBQcm9DYXJlIiwic2xhdWdodGVyRGF0ZSI6MTY2ODAzODc2OCwidW5pdHMiOjk4MDB9.gi5sWJn3yGwDugozTxCb7VJiOVCbdip_ATklUKtAzcNWmJ2qe4tJe2w_YPfALMHqnHkv2ulv98Ff3AJ8SJ_rRQ



### slaughterhouse : orderAnalysis :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiTS1tWDlFMW1ySUxPckVIM1BNVi1hSnZ6OEFFQmFVZkxMLXlLWElkUVJ4SSIsInkiOiJpeExJamM1VFczYS1YNEFZdkVrSEx1bm93NGk2NjB3cGNGZnpmdVJzUS1JIn19.eyJiYXRjaElkIjoiUzFCMSIsImxhYm9yYXRvcnlFdGhlcmV1bUFkZHJlc3MiOiIweEUwNjMxMjIzRjkzMThhOGIxMTg0M2UzRjI0QmQ0MEQzZDFkYzgyRGYiLCJvcE5hbWUiOiJvcmRlckFuYWx5c2lzIiwib3JkZXJJZCI6IkxhYjAwMiJ9.FoDWYvxPhG7FISCRJWUSXpLJi0H1KbpeS1ert8IwEokvKmuUfMaamXg5HJ7Z2iqHtEtr8gAjJJJDK-D6p2vVFQ



### slaughterhouse : VERIFY orderAnalysis :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiTS1tWDlFMW1ySUxPckVIM1BNVi1hSnZ6OEFFQmFVZkxMLXlLWElkUVJ4SSIsInkiOiJpeExJamM1VFczYS1YNEFZdkVrSEx1bm93NGk2NjB3cGNGZnpmdVJzUS1JIn19.eyJiYXRjaElkIjoiUzFCMSIsImxhYm9yYXRvcnlFdGhlcmV1bUFkZHJlc3MiOiIweEUwNjMxMjIzRjkzMThhOGIxMTg0M2UzRjI0QmQ0MEQzZDFkYzgyRGYiLCJvcE5hbWUiOiJvcmRlckFuYWx5c2lzIiwib3JkZXJJZCI6IkxhYjAwMiJ9.FoDWYvxPhG7FISCRJWUSXpLJi0H1KbpeS1ert8IwEokvKmuUfMaamXg5HJ7Z2iqHtEtr8gAjJJJDK-D6p2vVFQ



### slaughterhouse : releaseBatch :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiTS1tWDlFMW1ySUxPckVIM1BNVi1hSnZ6OEFFQmFVZkxMLXlLWElkUVJ4SSIsInkiOiJpeExJamM1VFczYS1YNEFZdkVrSEx1bm93NGk2NjB3cGNGZnpmdVJzUS1JIn19.eyJiYXRjaElkIjoiUzFCMSIsImRlc3RpbmF0aW9ucyI6W10sIm9wTmFtZSI6InJlbGVhc2VCYXRjaCJ9.yZU3Q4cuh7kPF6Li4qjhS4Bo1GF13IBVdeSJlkgDBWBi3QLuUvC3SlcjmGS-d2nyTe_k6NZ9PQztu4qtPzPs0Q



### slaughterhouse : VERIFY releaseBatch :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiTS1tWDlFMW1ySUxPckVIM1BNVi1hSnZ6OEFFQmFVZkxMLXlLWElkUVJ4SSIsInkiOiJpeExJamM1VFczYS1YNEFZdkVrSEx1bm93NGk2NjB3cGNGZnpmdVJzUS1JIn19.eyJiYXRjaElkIjoiUzFCMSIsImRlc3RpbmF0aW9ucyI6W10sIm9wTmFtZSI6InJlbGVhc2VCYXRjaCJ9.yZU3Q4cuh7kPF6Li4qjhS4Bo1GF13IBVdeSJlkgDBWBi3QLuUvC3SlcjmGS-d2nyTe_k6NZ9PQztu4qtPzPs0Q



### slaughterhouse : getBatch :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiTS1tWDlFMW1ySUxPckVIM1BNVi1hSnZ6OEFFQmFVZkxMLXlLWElkUVJ4SSIsInkiOiJpeExJamM1VFczYS1YNEFZdkVrSEx1bm93NGk2NjB3cGNGZnpmdVJzUS1JIn19.eyJiYXRjaElkIjoiUzFCMSIsIm9wTmFtZSI6ImdldEJhdGNoIn0.wCWyQcnXw7G8lz2e1DSEOB4Fga8AQlS9K7bmH1wTZJI918Klxnf20DtUF2LsNLujpq7t7lc_77MzioLwnDPUUg



### slaughterhouse : getProductionChain :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiTS1tWDlFMW1ySUxPckVIM1BNVi1hSnZ6OEFFQmFVZkxMLXlLWElkUVJ4SSIsInkiOiJpeExJamM1VFczYS1YNEFZdkVrSEx1bm93NGk2NjB3cGNGZnpmdVJzUS1JIn19.eyJiYXRjaElkIjoiUzFCMSIsIm9wTmFtZSI6ImdldFByb2R1Y3Rpb25DaGFpbiJ9.GIdEdkogStbJHcHuQkCnKcVsWUpk7kOo-Lk0zZly0hB2UcEnb5vTbpd0Z2ot7ZJnNEnTrZXnOZMbCo_5RDo8gA



#############################
###   LABORATORY
#############################


### laboratory : pushDataForFarmer :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiOXo4UFF3X05PRURrWW9YRklTdVpZUzhuQ1B1ZjQ2WV9ya0JhWmFTeXVMbyIsInkiOiJvN19nXzNIUjV5M2o1RmtBanN6Mnc5SEJ3SFF5Ym9jOW9lZEFMZkY2X1hNIn19.eyJiYXRjaElkIjoiRjFCMSIsIm9wTmFtZSI6InB1c2hMYWJvcmF0b3J5RGF0YSIsIm9yZGVySWQiOiJMYWIwMDEiLCJzYWxtb25lbGxhU3RhdHVzIjoibmVnYXRpdmUiLCJ0ZXN0aW5nRGF0ZSI6MTY2ODAzODc2Nn0.0e1jIqsxH4U22WjM4PzXX2dULrPj92_n56TQmne5JxtSHRd0ICTawGhY9T1BrFvxNy7rw2tXDq0alpaH3nkzpg



### laboratory : VERIFY pushDataForFarmer :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiOXo4UFF3X05PRURrWW9YRklTdVpZUzhuQ1B1ZjQ2WV9ya0JhWmFTeXVMbyIsInkiOiJvN19nXzNIUjV5M2o1RmtBanN6Mnc5SEJ3SFF5Ym9jOW9lZEFMZkY2X1hNIn19.eyJiYXRjaElkIjoiRjFCMSIsIm9wTmFtZSI6InB1c2hMYWJvcmF0b3J5RGF0YSIsIm9yZGVySWQiOiJMYWIwMDEiLCJzYWxtb25lbGxhU3RhdHVzIjoibmVnYXRpdmUiLCJ0ZXN0aW5nRGF0ZSI6MTY2ODAzODc2Nn0.0e1jIqsxH4U22WjM4PzXX2dULrPj92_n56TQmne5JxtSHRd0ICTawGhY9T1BrFvxNy7rw2tXDq0alpaH3nkzpg



### laboratory : pushDataPartialForFarmer :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiOXo4UFF3X05PRURrWW9YRklTdVpZUzhuQ1B1ZjQ2WV9ya0JhWmFTeXVMbyIsInkiOiJvN19nXzNIUjV5M2o1RmtBanN6Mnc5SEJ3SFF5Ym9jOW9lZEFMZkY2X1hNIn19.eyJiYXRjaElkIjoiRjFCMSIsIm9wTmFtZSI6InB1c2hMYWJvcmF0b3J5RGF0YSIsIm9yZGVySWQiOiJMYWIwMDEiLCJzYWxtb25lbGxhU3RhdHVzIjoibWF5YmUgbmVnYXRpdmUifQ.lab94bfMAs6L7jWABh2D7AuKdzsXemFmP0dTtR8bPSE7M2o3Dfbfbp3z8STXiQKA3R7kYabpbUO7M04HCgNy8w



### laboratory : VERIFY pushDataPartialForFarmer :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiOXo4UFF3X05PRURrWW9YRklTdVpZUzhuQ1B1ZjQ2WV9ya0JhWmFTeXVMbyIsInkiOiJvN19nXzNIUjV5M2o1RmtBanN6Mnc5SEJ3SFF5Ym9jOW9lZEFMZkY2X1hNIn19.eyJiYXRjaElkIjoiRjFCMSIsIm9wTmFtZSI6InB1c2hMYWJvcmF0b3J5RGF0YSIsIm9yZGVySWQiOiJMYWIwMDEiLCJzYWxtb25lbGxhU3RhdHVzIjoibWF5YmUgbmVnYXRpdmUifQ.lab94bfMAs6L7jWABh2D7AuKdzsXemFmP0dTtR8bPSE7M2o3Dfbfbp3z8STXiQKA3R7kYabpbUO7M04HCgNy8w



### laboratory : pushDataForSlaughterhouse :
POST http://localhost:42008/operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiOXo4UFF3X05PRURrWW9YRklTdVpZUzhuQ1B1ZjQ2WV9ya0JhWmFTeXVMbyIsInkiOiJvN19nXzNIUjV5M2o1RmtBanN6Mnc5SEJ3SFF5Ym9jOW9lZEFMZkY2X1hNIn19.eyJiYXRjaElkIjoiUzFCMSIsIm9wTmFtZSI6InB1c2hMYWJvcmF0b3J5RGF0YSIsIm9yZGVySWQiOiJMYWIwMDIiLCJzYWxtb25lbGxhU3RhdHVzIjoicG9zaXRpdmUiLCJ0ZXN0aW5nRGF0ZSI6MTY2ODAzODc2OH0.-KVHpOIUoQgJlJkkJZTFSd8TZ46l74LWVaKISijvvAJsnc3jXGe2yZZrLBV8fvjr9zhm_Nb840Gp7PwRpYSTGA



### laboratory : VERIFY pushDataForSlaughterhouse :
POST http://localhost:42008/verify-operation
Authorization: Bearer eyJhbGciOiJFUzI1NksiLCJqd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiOXo4UFF3X05PRURrWW9YRklTdVpZUzhuQ1B1ZjQ2WV9ya0JhWmFTeXVMbyIsInkiOiJvN19nXzNIUjV5M2o1RmtBanN6Mnc5SEJ3SFF5Ym9jOW9lZEFMZkY2X1hNIn19.eyJiYXRjaElkIjoiUzFCMSIsIm9wTmFtZSI6InB1c2hMYWJvcmF0b3J5RGF0YSIsIm9yZGVySWQiOiJMYWIwMDIiLCJzYWxtb25lbGxhU3RhdHVzIjoicG9zaXRpdmUiLCJ0ZXN0aW5nRGF0ZSI6MTY2ODAzODc2OH0.-KVHpOIUoQgJlJkkJZTFSd8TZ46l74LWVaKISijvvAJsnc3jXGe2yZZrLBV8fvjr9zhm_Nb840Gp7PwRpYSTGA

